/**
 * Константы чата.
 * Группированы в объект UI_CHAT для удобного доступа.
 */

import { UI_TEXT } from './ui'

/** Масштабные коэффициенты чата */
export const UI_CHAT_SCALE = {
	ICON: 0.75,
	META: 0.7,
	MEMBER: 0.9,
	SUBTEXT: 0.65,
	AVATAR_LARGE: 1.5,
	NAME: 1.1,
	FILE_ICON: 1.2,
	CONFIRM: 0.95,
	STATUS: 0.6,
	SPINNER: 0.5,
} as const

/** Текстовые константы чата */
export const UI_CHAT_TEXT = {
	REPLY: 'Ответить',
	SELECT: 'Выбрать',
	COPY: 'Копировать текст',
	PIN: 'Закрепить',
	UNPIN: 'Открепить',
	DELETE: UI_TEXT.DELETE,
	MESSAGE_PLACEHOLDER: 'Сообщение',
	SEND_ARIA: 'Отправить сообщение',
	ATTACH_ARIA: 'Прикрепить файл',
	CANCEL_REPLY_ARIA: 'Отменить ответ на сообщение',
	SHOW_COMMANDS_ARIA: 'Показать команды',
	EMOJI_ARIA: 'Открыть выбор эмодзи',
	FILE_SELECT_ARIA: 'Выбор файлов для прикрепления',
	SEARCH_ARIA: 'Поиск по сообщениям',
	INFO_ARIA: 'Информация о чате',
	DELETE_CONFIRM: 'Удалить сообщения?',
	REPLY_ARIA: 'Ответить на сообщение',
	SELECT_ARIA: 'Выбрать сообщение',
	TYPING_SUFFIX: 'печатает',
	TYPING_LABEL: 'Печатает',
	SEARCH_CLOSE: 'Закрыть поиск',
	PINNED_MESSAGE: 'Закреплённое сообщение',
	PINNED_COUNTER: 'из',
	PREV_PINNED_ARIA: 'Предыдущее закреплённое сообщение',
	NEXT_PINNED_ARIA: 'Следующее закреплённое сообщение',
	UNPIN_ARIA: 'Открепить сообщение',
	PHOTO: 'Фото',
	FILE: 'Файл',
	SELECTED_PREFIX: 'Выбрано:',
	FORWARD: 'Переслать',
	CANCEL: UI_TEXT.CANCEL,
	WRITE_MESSAGE: 'Написать сообщение',
	ROLE: 'Роль',
	WARNINGS: 'Предупреждения',
	BACK_TO_LIST: 'Назад к списку',
	NO_MEDIA: 'Нет медиафайлов',
	NO_FILES: 'Нет файлов',
	NO_LINKS: 'Нет ссылок',
	PROFILE: 'Профиль',
	INFORMATION: 'Информация',
	PARTICIPANTS: 'Участники',
	INFO_TAB: 'Инфо',
	MEDIA_TAB: 'Медиа',
	FILES_TAB: 'Файлы',
	LINKS_TAB: 'Ссылки',
	DEMOTE: 'Разжаловать',
	MAKE_ADMIN: 'Сделать админом',
	EXCLUDE: 'Исключить',
	BAN: 'Забанить',
	PHONE: 'Телефон',
	VIOLATION: 'Нарушение правил общения',
	CLOSE_PANEL: 'Закрыть панель информации',
	PARTICIPANTS_SUFFIX: 'участников',
	PARTICIPANTS_TITLE: 'Участники группы',
	MEMBER_ACTIONS: 'Действия с участником',
	DOWNLOAD_IMAGE: 'Скачать изображение',
	DOWNLOAD_FILE: 'Скачать файл',
	ADD_REACTION: 'Поставить реакцию',
	MESSAGE_INPUT: 'Напишите сообщение...',
	QUICK_REPLY: 'Быстрый ответ:',
	REMOVE_ATTACHMENT: 'Удалить вложение',
	INSERT_EMOJI: 'Вставить эмодзи',
	ADMIN: 'Администратор',
	MEMBER: 'Участник',
	ONLINE: 'в сети',
	OFFLINE: 'не в сети',
	SEARCH_PLACEHOLDER: 'Поиск по сообщениям...',
	DELETE_SINGLE_CONFIRM: 'Вы действительно хотите удалить это сообщение? Действие необратимо.',
	DELETE_MULTI_CONFIRM: 'Вы действительно хотите удалить выбранные сообщения ({count})? Действие необратимо.',
	DEMO_GROUP_DESCRIPTION: 'Официальная группа мастерской Металл-Арт. Здесь мы обсуждаем текущие проекты, делимся эскизами, координируем работу кузнецов, скульпторов и дизайнеров. Пожалуйста, соблюдайте правила вежливого общения.',
	DEMO_PROFILE_DESCRIPTION: 'Анна — ведущий скульптор нашей мастерской с опытом работы более 10 лет. Специализируется на художественной бронзе и монументальной металлической пластике. Выпускница Академии Художеств.',
	DEMO_PHONE: '+7 (999) 123-45-67',
	DEMO_EMAIL: 'info@metal-art.ru',
} as const
