/**
 * Экспорт всех глобальных констант UI-библиотеки.
 *
 * Группированные объекты (для нового кода):
 *   import { UI_TEXT, UI_TIMING, UI_FONT_WEIGHT, UI_CHAT_TEXT, UI_EDITOR } from '@constants'
 *
 * Плоские реэкспорты (обратная совместимость):
 *   import { UI_FONT_WEIGHT_SEMIBOLD, UI_CHAT_SCALE_ICON } from '@constants'
 */

import { UI_ARIA, UI_CALENDAR, UI_COLOR_PICKER, UI_FILTER, UI_FONT_WEIGHT, UI_RATING, UI_SCALE, UI_SIZE, UI_TEXT, UI_TIMING, UI_TOUR } from './ui'
import { UI_CHAT_SCALE, UI_CHAT_TEXT } from './chat'
import { UI_EDITOR } from './editor'

export { UI_ARIA, UI_CALENDAR, UI_COLOR_PICKER, UI_FILTER, UI_FONT_WEIGHT, UI_RATING, UI_SCALE, UI_SIZE, UI_TEXT, UI_TIMING, UI_TOUR } from './ui'
export { UI_CHAT_SCALE, UI_CHAT_TEXT } from './chat'
export { UI_EDITOR } from './editor'

// ─── Обратная совместимость: плоские реэкспорты ───────────────────

// UI_TEXT
export const UI_EMPTY_TEXT = UI_TEXT.EMPTY
export const UI_NO_RESULTS_TEXT = UI_TEXT.NO_RESULTS
export const UI_SEARCH_PLACEHOLDER = UI_TEXT.SEARCH_PLACEHOLDER
export const UI_TODAY_TEXT = UI_TEXT.TODAY
export const UI_LOADING_TEXT = UI_TEXT.LOADING
export const UI_LOADING_ARIA = UI_TEXT.LOADING_ARIA
export const UI_LOAD_MORE_TEXT = UI_TEXT.LOAD_MORE
export const UI_IMAGE_ERROR_TEXT = UI_TEXT.IMAGE_ERROR
export const UI_FILE_STATUS_DONE = UI_TEXT.FILE_STATUS_DONE
export const UI_FILE_STATUS_ERROR = UI_TEXT.FILE_STATUS_ERROR
export const UI_FILE_STATUS_PENDING = UI_TEXT.FILE_STATUS_PENDING
export const UI_DELETE_TEXT = UI_TEXT.DELETE
export const UI_NO_COLOR_TEXT = UI_TEXT.NO_COLOR
export const UI_CANCEL_TEXT = UI_TEXT.CANCEL
export const UI_APPLY_TEXT = UI_TEXT.APPLY
export const UI_SELECT_PLACEHOLDER = UI_TEXT.SELECT_PLACEHOLDER
export const UI_SELECT_DATE_TEXT = UI_TEXT.SELECT_DATE
export const UI_EXPAND_TEXT = UI_TEXT.EXPAND
export const UI_COLLAPSE_TEXT = UI_TEXT.COLLAPSE
export const UI_FILE_SELECT_TEXT = UI_TEXT.FILE_SELECT
export const UI_FILE_DROP_TEXT = UI_TEXT.FILE_DROP
export const UI_FILE_MAX_SIZE_PREFIX = UI_TEXT.FILE_MAX_SIZE_PREFIX
export const UI_FILE_MAX_SIZE_SUFFIX = UI_TEXT.FILE_MAX_SIZE_SUFFIX
export const UI_FILE_MAX_COUNT_PREFIX = UI_TEXT.FILE_MAX_COUNT_PREFIX

// UI_ARIA
export const UI_BREADCRUMBS_ARIA = UI_ARIA.BREADCRUMBS
export const UI_CLOSE_ARIA = UI_ARIA.CLOSE
export const UI_PREV_YEAR_ARIA = UI_ARIA.PREV_YEAR
export const UI_PREV_MONTH_ARIA = UI_ARIA.PREV_MONTH
export const UI_NEXT_MONTH_ARIA = UI_ARIA.NEXT_MONTH
export const UI_NEXT_YEAR_ARIA = UI_ARIA.NEXT_YEAR
export const UI_SORT_ARIA = UI_ARIA.SORT
export const UI_PASSWORD_HIDE_ARIA = UI_ARIA.PASSWORD_HIDE
export const UI_PASSWORD_SHOW_ARIA = UI_ARIA.PASSWORD_SHOW

// UI_TIMING
export const UI_DEBOUNCE_DEFAULT_MS = UI_TIMING.DEBOUNCE_DEFAULT
export const UI_ANIMATION_DURATION_MS = UI_TIMING.ANIMATION_DURATION
export const UI_HOVER_DELAY_MS = UI_TIMING.HOVER_DELAY
export const UI_TRANSITION_DURATION_MS = UI_TIMING.TRANSITION_DURATION
export const UI_PROGRESS_INTERVAL_MS = UI_TIMING.PROGRESS_INTERVAL
export const UI_TOOLTIP_SHOW_DELAY_MS = UI_TIMING.TOOLTIP_SHOW_DELAY
export const UI_TOOLTIP_HIDE_DELAY_MS = UI_TIMING.TOOLTIP_HIDE_DELAY
export const UI_SLIDER_HOLD_INTERVAL_MS = UI_TIMING.SLIDER_HOLD_INTERVAL
export const UI_HIGHLIGHT_DURATION_MS = UI_TIMING.HIGHLIGHT_DURATION
export const UI_NOTIFICATION_AUTO_CLOSE_MS = UI_TIMING.NOTIFICATION_AUTO_CLOSE
export const UI_IMAGE_LOAD_TIMEOUT_MS = UI_TIMING.IMAGE_LOAD_TIMEOUT

// UI_SIZE
export const UI_PANEL_MAX_HEIGHT = UI_SIZE.PANEL_MAX_HEIGHT
export const UI_SIDEBAR_DEFAULT_WIDTH = UI_SIZE.SIDEBAR_DEFAULT_WIDTH
export const UI_MODAL_DEFAULT_WIDTH = UI_SIZE.MODAL_DEFAULT_WIDTH
export const UI_CONTEXT_MENU_DEFAULT_WIDTH = UI_SIZE.CONTEXT_MENU_WIDTH
export const UI_CONTEXT_MENU_DEFAULT_HEIGHT = UI_SIZE.CONTEXT_MENU_HEIGHT
export const UI_CHAT_DEFAULT_HEIGHT = UI_SIZE.CHAT_DEFAULT_HEIGHT
export const UI_SLIDER_DEFAULT_HEIGHT = UI_SIZE.SLIDER_DEFAULT_HEIGHT
export const UI_IMAGE_LOADING_MIN_HEIGHT = UI_SIZE.IMAGE_LOADING_MIN_HEIGHT

// UI_SCALE
export const UI_SCALE_SMALL = UI_SCALE.SMALL
export const UI_SCALE_MEDIUM = UI_SCALE.MEDIUM
export const UI_SCALE_LARGE = UI_SCALE.LARGE
export const UI_SCALE_AUTOCOMPLETE = UI_SCALE.AUTOCOMPLETE

// UI_FONT_WEIGHT
export const UI_FONT_WEIGHT_MEDIUM = UI_FONT_WEIGHT.MEDIUM
export const UI_FONT_WEIGHT_SEMIBOLD = UI_FONT_WEIGHT.SEMIBOLD
export const UI_FONT_WEIGHT_BOLD = UI_FONT_WEIGHT.BOLD

// UI_TOUR
export const UI_SKIP_TOUR_TEXT = UI_TOUR.SKIP
export const UI_NEXT_TEXT = UI_TOUR.NEXT
export const UI_PREV_TEXT = UI_TOUR.PREV
export const UI_FINISH_TOUR_TEXT = UI_TOUR.FINISH
export const UI_TOUR_TITLE = UI_TOUR.TITLE

// UI_FILTER
export const UI_FILTER_COLUMN_TEXT = UI_FILTER.COLUMN
export const UI_FILTER_CONDITION_TEXT = UI_FILTER.CONDITION
export const UI_FILTER_VALUE_PLACEHOLDER = UI_FILTER.VALUE_PLACEHOLDER

// UI_CALENDAR
export const UI_CALENDAR_EVENT_TEXT = UI_CALENDAR.EVENT_TEXT

// UI_CHAT_SCALE
export const UI_CHAT_SCALE_ICON = UI_CHAT_SCALE.ICON
export const UI_CHAT_SCALE_META = UI_CHAT_SCALE.META
export const UI_CHAT_SCALE_MEMBER = UI_CHAT_SCALE.MEMBER
export const UI_CHAT_SCALE_SUBTEXT = UI_CHAT_SCALE.SUBTEXT
export const UI_CHAT_SCALE_AVATAR_LARGE = UI_CHAT_SCALE.AVATAR_LARGE
export const UI_CHAT_SCALE_NAME = UI_CHAT_SCALE.NAME
export const UI_CHAT_SCALE_FILE_ICON = UI_CHAT_SCALE.FILE_ICON
export const UI_CHAT_SCALE_CONFIRM = UI_CHAT_SCALE.CONFIRM
export const UI_CHAT_SCALE_STATUS = UI_CHAT_SCALE.STATUS
export const UI_CHAT_SCALE_SPINNER = UI_CHAT_SCALE.SPINNER

// UI_CHAT_TEXT
export const UI_CHAT_REPLY = UI_CHAT_TEXT.REPLY
export const UI_CHAT_SELECT = UI_CHAT_TEXT.SELECT
export const UI_CHAT_COPY_TEXT = UI_CHAT_TEXT.COPY
export const UI_CHAT_PIN = UI_CHAT_TEXT.PIN
export const UI_CHAT_UNPIN = UI_CHAT_TEXT.UNPIN
export const UI_CHAT_DELETE = UI_CHAT_TEXT.DELETE
export const UI_CHAT_MESSAGE_PLACEHOLDER = UI_CHAT_TEXT.MESSAGE_PLACEHOLDER
export const UI_CHAT_SEND_ARIA = UI_CHAT_TEXT.SEND_ARIA
export const UI_CHAT_ATTACH_ARIA = UI_CHAT_TEXT.ATTACH_ARIA
export const UI_CHAT_CANCEL_REPLY_ARIA = UI_CHAT_TEXT.CANCEL_REPLY_ARIA
export const UI_CHAT_SHOW_COMMANDS_ARIA = UI_CHAT_TEXT.SHOW_COMMANDS_ARIA
export const UI_CHAT_EMOJI_ARIA = UI_CHAT_TEXT.EMOJI_ARIA
export const UI_CHAT_FILE_SELECT_ARIA = UI_CHAT_TEXT.FILE_SELECT_ARIA
export const UI_CHAT_SEARCH_ARIA = UI_CHAT_TEXT.SEARCH_ARIA
export const UI_CHAT_INFO_ARIA = UI_CHAT_TEXT.INFO_ARIA
export const UI_CHAT_DELETE_CONFIRM = UI_CHAT_TEXT.DELETE_CONFIRM
export const UI_CHAT_REPLY_ARIA = UI_CHAT_TEXT.REPLY_ARIA
export const UI_CHAT_SELECT_ARIA = UI_CHAT_TEXT.SELECT_ARIA
export const UI_CHAT_TYPING_SUFFIX = UI_CHAT_TEXT.TYPING_SUFFIX
export const UI_CHAT_TYPING_LABEL = UI_CHAT_TEXT.TYPING_LABEL
export const UI_CHAT_SEARCH_CLOSE = UI_CHAT_TEXT.SEARCH_CLOSE
export const UI_CHAT_PINNED_MESSAGE = UI_CHAT_TEXT.PINNED_MESSAGE
export const UI_CHAT_PINNED_COUNTER = UI_CHAT_TEXT.PINNED_COUNTER
export const UI_CHAT_PREV_PINNED_ARIA = UI_CHAT_TEXT.PREV_PINNED_ARIA
export const UI_CHAT_NEXT_PINNED_ARIA = UI_CHAT_TEXT.NEXT_PINNED_ARIA
export const UI_CHAT_UNPIN_ARIA = UI_CHAT_TEXT.UNPIN_ARIA
export const UI_CHAT_PHOTO = UI_CHAT_TEXT.PHOTO
export const UI_CHAT_FILE = UI_CHAT_TEXT.FILE
export const UI_CHAT_SELECTED_PREFIX = UI_CHAT_TEXT.SELECTED_PREFIX
export const UI_CHAT_FORWARD = UI_CHAT_TEXT.FORWARD
export const UI_CHAT_CANCEL = UI_CHAT_TEXT.CANCEL
export const UI_CHAT_WRITE_MESSAGE = UI_CHAT_TEXT.WRITE_MESSAGE
export const UI_CHAT_ROLE = UI_CHAT_TEXT.ROLE
export const UI_CHAT_WARNINGS = UI_CHAT_TEXT.WARNINGS
export const UI_CHAT_BACK_TO_LIST = UI_CHAT_TEXT.BACK_TO_LIST
export const UI_CHAT_NO_MEDIA = UI_CHAT_TEXT.NO_MEDIA
export const UI_CHAT_NO_FILES = UI_CHAT_TEXT.NO_FILES
export const UI_CHAT_NO_LINKS = UI_CHAT_TEXT.NO_LINKS
export const UI_CHAT_PROFILE = UI_CHAT_TEXT.PROFILE
export const UI_CHAT_INFORMATION = UI_CHAT_TEXT.INFORMATION
export const UI_CHAT_PARTICIPANTS = UI_CHAT_TEXT.PARTICIPANTS
export const UI_CHAT_INFO_TAB = UI_CHAT_TEXT.INFO_TAB
export const UI_CHAT_MEDIA_TAB = UI_CHAT_TEXT.MEDIA_TAB
export const UI_CHAT_FILES_TAB = UI_CHAT_TEXT.FILES_TAB
export const UI_CHAT_LINKS_TAB = UI_CHAT_TEXT.LINKS_TAB
export const UI_CHAT_DEMOTE = UI_CHAT_TEXT.DEMOTE
export const UI_CHAT_MAKE_ADMIN = UI_CHAT_TEXT.MAKE_ADMIN
export const UI_CHAT_EXCLUDE = UI_CHAT_TEXT.EXCLUDE
export const UI_CHAT_BAN = UI_CHAT_TEXT.BAN
export const UI_CHAT_PHONE = UI_CHAT_TEXT.PHONE
export const UI_CHAT_VIOLATION = UI_CHAT_TEXT.VIOLATION
export const UI_CHAT_CLOSE_PANEL = UI_CHAT_TEXT.CLOSE_PANEL
export const UI_CHAT_PARTICIPANTS_SUFFIX = UI_CHAT_TEXT.PARTICIPANTS_SUFFIX
export const UI_CHAT_PARTICIPANTS_TITLE = UI_CHAT_TEXT.PARTICIPANTS_TITLE
export const UI_CHAT_MEMBER_ACTIONS = UI_CHAT_TEXT.MEMBER_ACTIONS
export const UI_CHAT_DOWNLOAD_IMAGE = UI_CHAT_TEXT.DOWNLOAD_IMAGE
export const UI_CHAT_DOWNLOAD_FILE = UI_CHAT_TEXT.DOWNLOAD_FILE
export const UI_CHAT_ADD_REACTION = UI_CHAT_TEXT.ADD_REACTION
export const UI_CHAT_MESSAGE_INPUT = UI_CHAT_TEXT.MESSAGE_INPUT
export const UI_CHAT_QUICK_REPLY = UI_CHAT_TEXT.QUICK_REPLY
export const UI_CHAT_REMOVE_ATTACHMENT = UI_CHAT_TEXT.REMOVE_ATTACHMENT
export const UI_CHAT_INSERT_EMOJI = UI_CHAT_TEXT.INSERT_EMOJI
export const UI_CHAT_ADMIN = UI_CHAT_TEXT.ADMIN
export const UI_CHAT_MEMBER = UI_CHAT_TEXT.MEMBER
export const UI_CHAT_ONLINE = UI_CHAT_TEXT.ONLINE
export const UI_CHAT_OFFLINE = UI_CHAT_TEXT.OFFLINE

// UI_EDITOR
export const UI_EDITOR_BOLD = UI_EDITOR.BOLD
export const UI_EDITOR_ITALIC = UI_EDITOR.ITALIC
export const UI_EDITOR_UNDERLINE = UI_EDITOR.UNDERLINE
export const UI_EDITOR_STRIKETHROUGH = UI_EDITOR.STRIKETHROUGH
export const UI_EDITOR_TEXT_COLOR = UI_EDITOR.TEXT_COLOR
export const UI_EDITOR_TEXT_COLOR_RESET = UI_EDITOR.TEXT_COLOR_RESET
export const UI_EDITOR_BG_COLOR = UI_EDITOR.BG_COLOR
export const UI_EDITOR_BG_COLOR_RESET = UI_EDITOR.BG_COLOR_RESET
export const UI_EDITOR_ALIGN_LEFT = UI_EDITOR.ALIGN_LEFT
export const UI_EDITOR_ALIGN_CENTER = UI_EDITOR.ALIGN_CENTER
export const UI_EDITOR_ALIGN_RIGHT = UI_EDITOR.ALIGN_RIGHT
export const UI_EDITOR_ALIGN_JUSTIFY = UI_EDITOR.ALIGN_JUSTIFY
export const UI_EDITOR_LIST_BULLET = UI_EDITOR.LIST_BULLET
export const UI_EDITOR_LIST_NUMBERED = UI_EDITOR.LIST_NUMBERED
export const UI_EDITOR_FORMAT = UI_EDITOR.FORMAT
export const UI_EDITOR_LINK = UI_EDITOR.LINK
export const UI_EDITOR_IMAGE = UI_EDITOR.IMAGE
export const UI_EDITOR_VIDEO = UI_EDITOR.VIDEO
export const UI_EDITOR_QUOTE = UI_EDITOR.QUOTE
export const UI_EDITOR_CODE_BLOCK = UI_EDITOR.CODE_BLOCK
export const UI_EDITOR_CLEAR_FORMAT = UI_EDITOR.CLEAR_FORMAT
export const UI_EDITOR_DIVIDER = UI_EDITOR.DIVIDER
export const UI_EDITOR_VISUAL_MODE = UI_EDITOR.VISUAL_MODE
export const UI_EDITOR_CODE_MODE = UI_EDITOR.CODE_MODE
export const UI_EDITOR_PARAGRAPH = UI_EDITOR.PARAGRAPH
export const UI_EDITOR_HEADING_PREFIX = UI_EDITOR.HEADING_PREFIX
export const UI_EDITOR_WIDTH = UI_EDITOR.WIDTH
export const UI_EDITOR_HEIGHT = UI_EDITOR.HEIGHT
export const UI_EDITOR_APPLY = UI_EDITOR.APPLY
export const UI_EDITOR_DELETE = UI_EDITOR.DELETE

// UI_COLOR_PICKER
export const UI_COLOR_PICKER_SELECTED_COLOR = UI_COLOR_PICKER.SELECTED_COLOR
export const UI_COLOR_PICKER_SATURATION_BRIGHTNESS = UI_COLOR_PICKER.SATURATION_BRIGHTNESS
export const UI_COLOR_PICKER_HUE = UI_COLOR_PICKER.HUE
export const UI_COLOR_PICKER_HEX_VALUE = UI_COLOR_PICKER.HEX_VALUE
export const UI_COLOR_PICKER_PRESET = UI_COLOR_PICKER.PRESET

// UI_RATING
export const UI_RATING_ARIA_PREFIX = UI_RATING.ARIA_PREFIX

// UI_CHAT_TEXT (new)
export const UI_CHAT_SEARCH_PLACEHOLDER = UI_CHAT_TEXT.SEARCH_PLACEHOLDER
export const UI_CHAT_DELETE_SINGLE_CONFIRM = UI_CHAT_TEXT.DELETE_SINGLE_CONFIRM
export const UI_CHAT_DELETE_MULTI_CONFIRM = UI_CHAT_TEXT.DELETE_MULTI_CONFIRM
