/**
 * Экспорт всех глобальных констант UI-библиотеки.
 *
 * Группированные объекты:
 *   import { UI_TEXT, UI_TIMING, UI_FONT_WEIGHT, UI_CHAT_TEXT, UI_EDITOR } from '@constants'
 */

export { UI_ARIA, UI_CALENDAR, UI_COLOR_PICKER, UI_FILTER, UI_FONT_WEIGHT, UI_RATING, UI_SCALE, UI_SIZE, UI_TEXT, UI_TIMING, UI_TOUR, CALENDAR_GRID_CELLS, MS_PER_DAY, UI_PROGRESS_STEP_MIN, UI_PROGRESS_STEP_RANGE, SIZE_SCALE_DEFAULT, SIZE_SCALE_OFFSET, MODAL_CLOSE_BUTTON_PADDING, DEFAULT_VARIANT } from './ui'
export { UI_CHAT_SCALE, UI_CHAT_TEXT } from './chat'
export { UI_EDITOR } from './editor'
export {
	TABLE_DEFAULT_PAGE_SIZE,
	TABLE_DEFAULT_SKELETON_ROWS,
	TABLE_EXPAND_TRANSITION_DURATION,
	TABLE_INFINITE_SCROLL_THRESHOLD,
	TABLE_MIN_COL_WIDTH,
	TABLE_PAGINATION_MAX_VISIBLE,
	TABLE_ROW_EXPAND_WIDTH,
	TABLE_ROW_NUMBER_WIDTH,
	TABLE_ROW_SELECTION_WIDTH,
	TABLE_SEARCH_DEBOUNCE_MS,
	TABLE_SETTINGS_MAX_HEIGHT,
} from './table'
